# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Lab 0 Java CI with Maven

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    types: [assigned, opened, synchronize, reopened, edited, ready_for_review]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests with Maven
      run: mvn --no-transfer-progress test exec:java -Dexec.args="--disable-banner --class-path=$GITHUB_WORKSPACE/target/test-classes --scan-classpath"
    - name: Run checkstyle with Maven
      run: mvn --no-transfer-progress clean test -Dcheckstyle.violationSeverity=warning
